### PR TITLE
fix-predicate-timestamp-and-decimal

### LINKED ISSUE #30: [Bug] Predicate Timestamp and Decimal cannot compare.
# Timestamp

```
SELECT ts 
FROM paimon.default.test_timestamp
WHERE ts = TIMESTAMP '2023-01-01 15:01:01.123
;
```

```
java.lang.ClassCastException: org.apache.paimon.data.Timestamp cannot be cast to java.lang.Long
	at java.lang.Long.compareTo(Long.java:54)
	at org.apache.paimon.predicate.CompareUtils.compareLiteral(CompareUtils.java:31)
	at org.apache.paimon.predicate.GreaterOrEqual.test(GreaterOrEqual.java:43)
	at org.apache.paimon.predicate.NullFalseLeafBinaryFunction.test(NullFalseLeafBinaryFunction.java:53)
	at org.apache.paimon.predicate.LeafPredicate.test(LeafPredicate.java:113)
	at org.apache.paimon.predicate.And.test(And.java:60)
	at org.apache.paimon.predicate.CompoundPredicate.test(CompoundPredicate.java:63)
	at org.apache.paimon.operation.KeyValueFileStoreScan.filterWholeBucketByStats(KeyValueFileStoreScan.java:105)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.apache.paimon.operation.AbstractFileStoreScan.doPlan(AbstractFileStoreScan.java:328)
	at org.apache.paimon.operation.AbstractFileStoreScan.plan(AbstractFileStoreScan.java:212)
	at org.apache.paimon.table.source.snapshot.SnapshotReaderImpl.read(SnapshotReaderImpl.java:228)
	at org.apache.paimon.table.source.snapshot.FullStartingScanner.scan(FullStartingScanner.java:51)
	at org.apache.paimon.table.source.InnerTableScanImpl.plan(InnerTableScanImpl.java:83)
	at org.apache.paimon.presto.PrestoSplitManager.getSplits(PrestoSplitManager.java:50)
	at com.facebook.presto.split.SplitManager.getSplits(SplitManager.java:89)
	at com.facebook.presto.split.CloseableSplitSourceProvider.getSplits(CloseableSplitSourceProvider.java:52)
	at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.lambda$visitTableScan$0(SplitSourceFactory.java:157)
	at com.facebook.presto.sql.planner.LazySplitSource.getDelegate(LazySplitSource.java:96)
	at com.facebook.presto.sql.planner.LazySplitSource.getConnectorId(LazySplitSource.java:48)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStageScheduler(SectionExecutionFactory.java:281)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:243)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:221)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:221)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createSectionExecutions(SectionExecutionFactory.java:167)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createStageExecutions(LegacySqlQueryScheduler.java:354)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.<init>(LegacySqlQueryScheduler.java:243)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createSqlQueryScheduler(LegacySqlQueryScheduler.java:172)
	at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:640)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:464)
	at com.facebook.presto.$gen.Presto_0_280_SNAPSHOT_fdc9bdf____20231225_052917_1.run(Unknown Source)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:306)
	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$8(LocalDispatchQuery.java:211)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

# Decimal

```
SELECT c2 FROM paimon.default.test_decimal where c2 = 123.456;
```

```
Error Message: java.math.BigDecimal cannot be cast to org.apache.paimon.data.Decimal
Error Code: 65536
Error Type: INTERNAL_ERROR
Failure Type: java.lang.ClassCastException
Failure Message: java.math.BigDecimal cannot be cast to org.apache.paimon.data.Decimal
Failure Stack: org.apache.paimon.data.GenericRow.getDecimal(GenericRow.java:176)
org.apache.paimon.data.InternalRow.lambda$createFieldGetter$d63141e$1(InternalRow.java:186)
org.apache.paimon.data.serializer.InternalRowSerializer.toBinaryRow(InternalRowSerializer.java:158)
org.apache.paimon.operation.ScanBucketFilter.hash(ScanBucketFilter.java:134)
org.apache.paimon.operation.ScanBucketFilter.lambda$create$0(ScanBucketFilter.java:126)
org.apache.paimon.operation.ScanBucketFilter.assembleRows(ScanBucketFilter.java:148)
org.apache.paimon.operation.ScanBucketFilter.create(ScanBucketFilter.java:124)
org.apache.paimon.operation.ScanBucketFilter.setBucketKeyFilter(ScanBucketFilter.java:65)
org.apache.paimon.KeyValueFileStore$1.pushdown(KeyValueFileStore.java:188)
org.apache.paimon.operation.KeyValueFileStoreScan.withKeyFilter(KeyValueFileStoreScan.java:75)
org.apache.paimon.table.PrimaryKeyFileStoreTable.lambda$nonPartitionFilterConsumer$0(PrimaryKeyFileStoreTable.java:145)
org.apache.paimon.table.source.snapshot.SnapshotReaderImpl.withFilter(SnapshotReaderImpl.java:183)
org.apache.paimon.table.source.InnerTableScanImpl.withFilter(InnerTableScanImpl.java:59)
org.apache.paimon.table.source.ReadBuilderImpl.newScan(ReadBuilderImpl.java:94)
org.apache.paimon.presto.PrestoSplitManager.getSplits(PrestoSplitManager.java:50)
com.facebook.presto.split.SplitManager.getSplits(SplitManager.java:89)
com.facebook.presto.split.CloseableSplitSourceProvider.getSplits(CloseableSplitSourceProvider.java:52)
com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.lambda$visitTableScan$0(SplitSourceFactory.java:157)
com.facebook.presto.sql.planner.LazySplitSource.getDelegate(LazySplitSource.java:96)
com.facebook.presto.sql.planner.LazySplitSource.getConnectorId(LazySplitSource.java:48)
com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStageScheduler(SectionExecutionFactory.java:281)
com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:243)
com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:221)
com.facebook.presto.execution.scheduler.SectionExecutionFactory.createSectionExecutions(SectionExecutionFactory.java:167)
com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createStageExecutions(LegacySqlQueryScheduler.java:354)
com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.<init>(LegacySqlQueryScheduler.java:243)
com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createSqlQueryScheduler(LegacySqlQueryScheduler.java:172)
com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:640)
com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:464)
```

### PR DESCRIPTION
**Pull request by feloxx**
fix #30 

presto paimon connector when the predicate pushdown and read data, the data in the file was converted to paimon Timestamp type, the default time zone was not used with the system default, so the error was caused.

image

---

TimeType will also have problems, fix it in the next pr.

### CODE REVIEW

File: paimon-presto-common/src/main/java/org/apache/paimon/presto/PrestoFilterConverter.java [hunk 1]
```diff
@@ -208,8 +212,23 @@ private Object getLiteralValue(Type type, Object prestoNativeValue) {
             return Math.toIntExact(((Long) prestoNativeValue));
         }
 
-        if (type instanceof TimestampType || type instanceof TimeType) {
-            return TimeUnit.MILLISECONDS.toMicros((Long) prestoNativeValue);
+        if (type instanceof TimeType) {
+            return Timestamp.fromEpochMillis((Long) prestoNativeValue);
```
Comment (JingsongLi) [inline paimon-presto-common/src/main/java/org/apache/paimon/presto/PrestoFilterConverter.java:216]: Paimon time type is a Int, see InternalRow documentation.

**Comment by feloxx** [comment]
image

**Review by JingsongLi — APPROVED** [review]
+1
